
export const CREATE_BILL_INVOICE_REQUEST = "CREATE_BILL_INVOICE_REQUEST";
export const CREATE_BILL_INVOICE_SUCCESS = "CREATE_BILL_INVOICE_SUCCESS";
export const CREATE_BILL_INVOICE_FAIL = "CREATE_BILL_INVOICE_FAIL";
export const CREATE_BILL_INVOICE_RESET = "CREATE_BILL_INVOICE_RESET";



export const GET_BILL_INVOICE_REQUEST = "GET_BILL_INVOICE_REQUEST";
export const GET_BILL_INVOICE_SUCCESS = "GET_BILL_INVOICE_SUCCESS";
export const GET_BILL_INVOICE_FAIL = "GET_BILL_INVOICE_FAIL";
export const GET_BILL_INVOICE_RESET = "GET_BILL_INVOICE_RESET";
