export const SAVE_CONTACT_DETAILS_REQUEST = "SAVE_CONTACT_DETAILS_REQUEST";
export const SAVE_CONTACT_DETAILS_SUCCESS = "SAVE_CONTACT_DETAILS_SUCCESS";
export const SAVE_CONTACT_DETAILS_ERROR = "SAVE_CONTACT_DETAILS_ERROR";
export const SAVE_CONTACT_DETAILS_RESET = "SAVE_CONTACT_DETAILS_RESET";
